# Generated by Django 3.2.7 on 2022-04-21 23:54
from django.core.exceptions import FieldError
from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q

from upapp.models import UserProfileSection


def deleteSections(apps, schema_editor):
    try:
        filter = Q(title__iregex=f'^.*industry.*$') | Q(title__iregex=f'^.*interest.*$')
        UserProfileSection.objects.filter(filter).delete()
    except FieldError:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('upapp', '0079_employerjob_isfulltime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilesection',
            name='description',
        ),
        migrations.AddField(
            model_name='userprofilesection',
            name='sectionType',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userjobapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobApplication', to='upapp.user'),
        ),
        migrations.RunPython(deleteSections),
    ]
